@url=http://localhost:8000

### Create product
POST {{url}}/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

{
    "shop": "67081b7e56c522fc28e49509",
    "product_name": "Laptop Acer Nitro 5 Tiger AN515-58-5935 i5-12450H|8GB|512GB|RTX™ 4050 6GB|15.6'",
    "product_type": "electronics",
    "product_quantity": 50,
    "product_quantity_sold": 0,
    "product_price": 950,
    "product_desc": "Đối với sản phẩm dưới 20 triệu quý khách hàng cung cấp thông tin VAT công ty hoặc cá nhân để xuất hóa đơn bảo hành sản phẩm. Trường hợp không cung cấp shop mặc định xuất theo thông tin tài khoản mua hàng.",
    "product_attribute": {
        "manufacturer": "Acer",
        "product_model": "AN515-58-5935",
        "color": ["Black"]
    },
    "isPublish": false
}

### Get unpublish products by shop
GET {{url}}/api/unpublished-products/670542ac3bbe8b943b33592b?limit=2&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg2OTEyMjIsImV4cCI6MTcyODY5MjEyMn0.XTPkyyMv_ulsQndEgRTtM_-cSqrVO3zwBVchmVv-0lRyty4mFICZSrocZxLnhQzOFslv6d6w5dG9X9GnEBuLojcu3Gv2NGbSuCMACFgQm2GoAzj_-qSMclEmTKTfLwNg0Lr-phI3RF2xgiywdOCp3iKpIruyV8PVLKhzNC_r5WMkLyBIrMMn4UMm5yhFRj-nUHzyzhWVVjNVy4-Wd8e9vBF-p8DQk0soZQuq6pSqTZXWbOMHtX5pqQIX0dnmn1Oy1OBQDJqfU6zz-2pfc7BjRJeeO8uykMDj7j1yIcLY4u4uppX5OTlYlIl-_-WzgMvJRLWnyghvLsZGAJvAlYWgNQ
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg2OTEyMjIsImV4cCI6MTc2MDI0ODgyMn0.OuUF2dSJjJP099r3UWfxrQkO68tcdspzQMZlQDvfqC02-XtwCCVbJqL4kHEj7Tma6F9IxoRHP_wTwgyn1g9jyGgCkaLEpepS1SnTJOpHpK4zLkNUpZucOB8vSu71eSXR2_LPtYJ2rwRuqhFZpopLfSvBtE17DqJVGsFORrMsjoX1r0vX9pb7jNpRcmECIC7LIc77GaXgQ_PKwjKkvCP6oHiC3KbbckSmp1hohUhurtcEMzHrN6nJCp57c7SrIn4TBrtXuJSIig6TfTKp8d7FTo2FsjaBl0GrKI7IJHwKbmIjVuivKT14a7FZQJ4TZ_3R-JmbXRaNbCXAhE5xCCWVOQ

### Get publish products by shop
GET {{url}}/api/published-products/670542ac3bbe8b943b33592b?limit=2&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Publish product by id
PATCH {{url}}/api/products/67081ba956c522fc28e4950f/publish
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Unpublish product by id
PATCH {{url}}/api/products/6707df93c439acaf43f4a0f3/unpublish
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Get products
GET {{url}}/api/products?limit=5&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Search products by keyword
GET {{url}}/api/products/search?keyword=Laptop&limit=5&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Update product by id
PUT {{url}}/api/products/67081ba956c522fc28e4950f
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA4MWI3ZTU2YzUyMmZjMjhlNDk1MDkiLCJuYW1lIjoiYXNob3AxMjMiLCJlbWFpbCI6InRyYW5kdWN2dTIyQGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwiX192IjowLCJpYXQiOjE3Mjg2NjM2MDgsImV4cCI6MTcyODY2NDUwOH0.FdPrt5lsTmf9_u1nKEHB7QVIjv3_HrUHlMr8AKR3ch3Lhmp6hCzsxn5k-RkYtnfL7IAqRIGO1nhejp1eGPqPG_uU1GmcZeRLEHU0nxPrdzEjaTDkSRRzCKephmURRVYF13IHoqk0WSIHw59jJKEB5UPC1hlvMBW6NFcg4ox_NSGLjohE2_KLOcIA6iSBpo9Z8HmM3-jnPTmbGPdSqqDgwgECw6KDAZjnxYkuqQ5YAmkWMGkMXfTXMDuYYemDXg0lC4-Zd9vQ_D3euYuG6ufkmnX8nfdNzAMjVUjEmQQUVJVHVIG-uZsmD0NTDlQoDpPCFC51LUs2xKobOCtTNxZddQ
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA4MWI3ZTU2YzUyMmZjMjhlNDk1MDkiLCJuYW1lIjoiYXNob3AxMjMiLCJlbWFpbCI6InRyYW5kdWN2dTIyQGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwiX192IjowLCJpYXQiOjE3Mjg2NjM2MDgsImV4cCI6MTc2MDIyMTIwOH0.N3UuByO_Q2nwAQUagOZjcaA8t0rMCHXzRSxv9ArNmcquCFS8a1fsjWXSO0qjhr46lJ8O29Fa7KB6r8R8k1tsDFKLyONseQnr9mjcG-rEUY_VVNcP6_j-YPZmtgvwe6IzF0ShglaMYd82D_IEg7SmYPxIKJpEm8gqsrti2w8d8V4CStQG639hTjuoYyUUiwrWJf0k1WOg2vLwfYJDQ-yBE7pS9ju_TFvFDqnbrf0vCFlUuTILlx0Mw3AFGQnRapt5IZ8OQOlXwNK-x4K8Mjeyx1AHf7QK1DXT-tgyGC_yPpeN89HUA7uRw0I-FAsrrtPLUET9EQUFNvqHsvqvYw_6Uw
Content-Type: application/json

{
    "shop": "67081b7e56c522fc28e49509",
    "product_name": "Kệ 123 Tầng Để Giày Dép Có Màng Chắn Bụi, Kệ Giày Dép 5 Tầng Khung Thép Carbon, Tặng Kèm 8 Móc Treo Đồ",
    "product_thumb": "",
    "product_type": "furniture",
    "product_images": [],
    "product_variation": [],
    "product_quantity": 100,
    "product_quantity_sold": 0,
    "product_price": 50,
    "product_desc": "Kệ giày giúp bạn lưu trữ và quản lý giày, dép một cách gọn gàng, ngăn nắp, giữ form giày, dép luôn đẹp như mới.",
    "product_attribute": {
        "manufacturer": "Kim Long",
        "material": "Plastic",
        "color": [ "Pink", "White", "Light Green" ]
    },
    "isPublish": true
}


###  Delete product by id
DELETE {{url}}/api/products/67081ba956c522fc28e4950f
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA4MWI3ZTU2YzUyMmZjMjhlNDk1MDkiLCJuYW1lIjoiYXNob3AxMjMiLCJlbWFpbCI6InRyYW5kdWN2dTIyQGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwiX192IjowLCJpYXQiOjE3Mjg2OTI1MTYsImV4cCI6MTcyODY5MzQxNn0.gXoaeUQ8HL3od5yPeU0bx1ibauWGvDoEXYKCRFHy3O5RPvyXWDgiUnCpeF94ePf_YZQS2RiP7IX6cBUED2mOzez6S0vLSO4zCIIrUBGbqKOCmUP0HJxAUk4rWEHrrD4jU54k0JTqVOwzDwQUtmaFyiBt8kmFQxGYjaGBGjgEkyh2qQFDV5Sh9V38ZvugueGRhaZeBvgaP_3w_fuO9r0d8uChuMd3sW7hCxhG_9Hi3swFxIFAcjy6FmxyOhJboZDwqlmAzTIEJ43s8C40aNfPA3LCMqOfM3U3Jte02KanwjUCJu4mlxkKz2RFW_grWaxxSpURhBbWs6uCjUv6XW5nNw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA4MWI3ZTU2YzUyMmZjMjhlNDk1MDkiLCJuYW1lIjoiYXNob3AxMjMiLCJlbWFpbCI6InRyYW5kdWN2dTIyQGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xMFQxODoyMjo1NC4xMjJaIiwiX192IjowLCJpYXQiOjE3Mjg2OTI1MTYsImV4cCI6MTc2MDI1MDExNn0.O-MUJRjZYdY5BkKhOwuysjIBRc3R1UK_HrgQTiEVw5K0Hbyp4Yf6QbojaXGM1swvRB7r08KfQzv4ynP_7yPaJNzJKi1TlLZuYEkJwcZ8N6vXodKoJ0WMCYJms6MC5mQjT5bo0JCp7FFdvbxsEF66PXKSZAy_4LNnY1DyiMrVwtT5mEa2_wnE4mH9tekI-ii2h32aNK7xPFaHC2KQrLLAmesYKuBRISor3iwsrenWmc-JTwmKOWjm2sL89MgVdCZAq6cjVULww8NwphZAh6wjzwq4dyjFz1WYHI_369osufp2Jpq3_k8FugXCu04sgcvxYpCK8dMruy2tsprWNtLiuA