@url=http://localhost:8000

### Create product
POST {{url}}/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

{
    "shop": "67081b7e56c522fc28e49509",
    "product_name": "Laptop Acer Nitro 5 Tiger AN515-58-5935 i5-12450H|8GB|512GB|RTX™ 4050 6GB|15.6'",
    "product_type": "electronics",
    "product_quantity": 50,
    "product_quantity_sold": 0,
    "product_price": 950,
    "product_desc": "Đối với sản phẩm dưới 20 triệu quý khách hàng cung cấp thông tin VAT công ty hoặc cá nhân để xuất hóa đơn bảo hành sản phẩm. Trường hợp không cung cấp shop mặc định xuất theo thông tin tài khoản mua hàng.",
    "product_attribute": {
        "manufacturer": "Acer",
        "product_model": "AN515-58-5935",
        "color": ["Black"]
    },
    "isPublish": false
}

### Get unpublish products by shop
GET {{url}}/api/unpublished-products/670542ac3bbe8b943b33592b?limit=2&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Get publish products by shop
GET {{url}}/api/published-products/670542ac3bbe8b943b33592b?limit=2&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Publish product by id
PATCH {{url}}/api/products/67081ba956c522fc28e4950f/publish
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Unpublish product by id
PATCH {{url}}/api/products/6707df93c439acaf43f4a0f3/unpublish
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Get products
GET {{url}}/api/products?limit=5&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q

### Search products by keyword
GET {{url}}/api/products/search?keyword=Laptop&limit=5&page=1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Njg4NzUsImV4cCI6MTcyODU2OTc3NX0.iVOHtFyuuISnM665ky0q2IXagPfe9xbKbFWCCfema6Cbv2s1N_wpKBTsMixCkRlmMsfzLaXjignE3eN9D0U6lxJTqPn8F0L8EPaQWPzsplmvfPX05TxzBXU-qaIdl3j6fxPlo79Kl0ofIHGUShaS7IOzku_5ihu30D1nz107Ee4FEikV3HVjNhLEW2_Nz7E8M8xr8-KMK2JSE3iri-jiFFdU8a0WOf2GC2aM7P1ugoXcZxQqG_iDHVVRX8Quhu0l8WEmnFi533n1sy28Dm6i-UX0jov8x1UadzZP9ullJveOw3qIvU9mNg2U06MuagzdvqzXtD7IYkutUdecazOzQw
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzA1NDJhYzNiYmU4Yjk0M2IzMzU5MmIiLCJuYW1lIjoidnV0cmFuc2hvcCIsImVtYWlsIjoidHJhbmR1Y3Z1MjM0QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0wOFQxNDozMzoxNi4yNzFaIiwiX192IjowLCJpYXQiOjE3Mjg1Mjk4NTMsImV4cCI6MTc2MDA4NzQ1M30.SuS-Mt2zUmcFxGTzuOri9KuxH6s3LLjXSFOmBwovaHqv5h4c2VP0YEOMEjqVygH0V5HdvMtGmtJTYDN3Eyi1IemcvukTlql6jt8O3DQCOnN96pH7rGmBojyIqTAqKy5A0aiXR-S9eShKjVStxzmCH-g-QGe4OMoGZFbaFWlPxIGaMhsQBqUlkIWWKy3TBP2rSmqrs5cJZDfJ3O9rPnt_M4h7cH2aLpEn4UECPCr7d-4k4nJUCuxiTCUVlbDIrblquuEXLtBJqA_OJyoMKF4-4Z7zIkr9SspbG1ZpQj0I1CSqP5N811r3FVjVAITaUoZ-7WG0m0YWLE5sMWvSsMzw-Q