@url = http://localhost:8000

### Get shop
GET {{url}}/api/shops?email=tranducvu34@gmail.com
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmYxN2Y0NzJiZjcyYzg0ODM4ZWE1OTgiLCJuYW1lIjoidnV0cmFuc2hvcDEyMyIsImVtYWlsIjoidHJhbmR1Y3Z1MzQ1QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yM1QxNDo0NjozMS44NTdaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yM1QxNDo0NjozMS44NTdaIiwiX192IjowLCJpYXQiOjE3MjcxMDYzMzEsImV4cCI6MTcyNzEwNjMzMn0.XsRJryRHqb_z_24uDVIN1Inoq1JaaaQW3PKtM9cSZimprH4Zp-g1oj5_I3KxRnfmGh_pT8peUayVNM0uEyHvZfYiXay0ej71yNZ1WYSZCpIZctx4Q9JSRS-__WWkNvftpOLsFArFt0P_ihCoob7SwokW6mse621M_khKE9lwhQFiOXz7dKAtMQW0z4gXyStO4gVT_4anvRYZhaU3ZGn4NcI6UC9-kN0_KbNZeDdZKWn_2xZ-Puf3SfZrQ1Ipu0Hm1kzSCqXb6oKzV_77b6SJH7MubGD3ScbHdPplRkFaEy0r8Qt7a7nPtEjihoE5lh4sQldtvQPF8wK8GcBuBl2aTA
X-Refresh: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmYxN2Y0NzJiZjcyYzg0ODM4ZWE1OTgiLCJuYW1lIjoidnV0cmFuc2hvcDEyMyIsImVtYWlsIjoidHJhbmR1Y3Z1MzQ1QGdtYWlsLmNvbSIsInBob25lIjoiMDk0NDY1MDU4OSIsInN0YXR1cyI6ImFjdGl2ZSIsInJvbGVzIjpbXSwiY3JlYXRlZEF0IjoiMjAyNC0wOS0yM1QxNDo0NjozMS44NTdaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0yM1QxNDo0NjozMS44NTdaIiwiX192IjowLCJpYXQiOjE3MjcxMTM1MTUsImV4cCI6MTc1ODY3MTExNX0.W1OiV40L9NZ_XBM5rfmR6MHtf1Sbj1EvdZvyl-Ypj9pwLOBd6KUJZtP5ueawOo3n1vjbZjtPC_VVnSvJEiGr1WIMYVJYALmfbUXtcLcEbjA_dtVn2C21xfx_cSPEGGzZxMigVK-PtNBHLcqyah1BEAEcLHu-HaYZ65dvCQVbNPkDrsfUT_zDrffV9MEVL2Q_7azrptJk1T8Hf0mJAbpW9or58al5FQspMwdZBijWJtEPJgKZ_I1t0xxbzy2OGQDJoabYzzASooB2OEEJe0c6fNlfD9L6mTY7gXNJWz-buN6rlig2C9G8dhspny6u5D4wbzmNwPe3iFpVjA5vLBkmQw

